import {
  Geist,
  Geist_Mono,
  Poppins,
  Noto_Sans_Canadian_Aboriginal,
} from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import LoadingBar from "@/public/src/components/LoadingBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <LoadingBar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
